---
services:
  - docker

env:
  matrix:
    - ROLE_OPTIONS="postgresql_version=9.4"
    - ROLE_OPTIONS="postgresql_version=9.5"
    - ROLE_OPTIONS="postgresql_version=9.6"

before_install:
  - make docker-pull

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
