---
- name: ensure postgres is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: set users
  postgresql_user:
    name: "{{item.name}}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_users}}"
  when: postgresql_users|length > 0
